syntax = "proto3";

option csharp_namespace = "Medinilla.Core.gRPC.Service";

import "Service/Types.proto";

package medinilla.core.grpc;

service OcppService {
    rpc SetVariables (SetVariablesRequest) returns (SetVariablesResponse) {}
    rpc GetVariables (GetVariablesRequest) returns (GetVariablesResponse) {}
    rpc GetBaseReport (GetBaseReportRequest) returns (GetBaseReportResponse) {}
    rpc Reset (ResetRequest) returns (ResetResponse) {}

    rpc FetchExecutedCommands (FetchExecutedCommandsRequest) returns (FetchExecutedCommandsResponse) {}
}