syntax = "proto3";

option csharp_namespace = "Medinilla.Core.gRPC.Service";

import "Contracts/UserSetVariablesRequest.proto";
import "Contracts/UserGetVariablesRequest.proto";
import "Contracts/CommandExecution.proto";
import "Contracts/ResetType.proto";

package medinilla.core.grpc;

message Error {
    bool has_error = 1;
    optional string message = 2;
}

message SetVariablesRequest {
    string client_identifier = 1;
    repeated UserSetVariablesRequest set_variable_data = 2;
}

message SetVariablesResponse {
    Error error = 1;
}

message GetVariablesRequest {
    string client_identifier = 1;
    repeated UserGetVariablesRequest get_variable_data = 2;
}

message GetVariablesResponse {
    Error error = 1;
}

message GetBaseReportRequest {
    string client_identifier = 1;
    string report_base = 2;
}

message GetBaseReportResponse {
    Error error = 1;
}

message ResetRequest {
    string client_identifier = 1;
    ResetType type = 2;
    optional int32 evse_id = 3;
}

message ResetResponse {
    Error error = 1;
}

message FetchExecutedCommandsRequest {
    string client_identifier = 1;
}

message FetchExecutedCommandsResponse {
    repeated CommandExecution executions = 1;
}
