syntax = "proto3";

option csharp_namespace = "Medinilla.Core.gRPC.Service";

import "Service/ocpp/SetVariablesAPI.proto";
import "Service/ocpp/GetVariablesAPI.proto";
import "Service/ocpp/GetBaseReportAPI.proto";
import "Service/ocpp/ResetAPI.proto";
import "Service/ocpp/RequestStartTransactionAPI.proto";
import "Service/ocpp/RequestStopTransactionAPI.proto";
import "Service/ocpp/FetchExecutedCommandsAPI.proto";

package medinilla.core.grpc;

service OcppService {
    rpc SetVariables (SetVariablesRequest) returns (SetVariablesResponse) {}
    rpc GetVariables (GetVariablesRequest) returns (GetVariablesResponse) {}
    rpc GetBaseReport (GetBaseReportRequest) returns (GetBaseReportResponse) {}
    rpc Reset (ResetRequest) returns (ResetResponse) {}
    rpc RequestStartTransaction (RequestStartTransactionRequest) returns (RequestStartTransactionResponse) {}
    rpc RequestStopTransaction (RequestStopTransactionRequest) returns (RequestStopTransactionResponse) {}

    rpc FetchExecutedCommands (FetchExecutedCommandsRequest) returns (FetchExecutedCommandsResponse) {}
}
