// <auto-generated />
using System;
using System.Text.Json;
using Medinilla.DataAccess.Relational;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Medinilla.Core.Service.Migrations
{
    [DbContext(typeof(MedinillaOcppDbContext))]
    [Migration("20251026220919_UpdateChargingStation")]
    partial class UpdateChargingStation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("core_account", (string)null);
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.Authorization.AuthorizationDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("AuthBlob")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ChargingStationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChargingStationId")
                        .IsUnique();

                    b.ToTable("core_auth_details", (string)null);
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.Authorization.AuthorizationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ActiveCredit")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ChargingStationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("core_auth_user", (string)null);
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.Authorization.IdToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorizationUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Blocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ChargingStationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsUnderTx")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationUserId");

                    b.HasIndex("ChargingStationId", "Token");

                    b.ToTable("core_id_token", (string)null);
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.ChargingStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<Guid>("AuthDetailsId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Booted")
                        .HasColumnType("boolean");

                    b.Property<string>("ClientIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LatestBootNotificationReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ClientIdentifier");

                    b.ToTable("core_charging_station", (string)null);
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.EvseConnector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChargingStationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("integer");

                    b.Property<string>("ConnectorStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EvseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChargingStationId");

                    b.ToTable("core_evse_connector", (string)null);
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChargingStationId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ChargingStationId");

                    b.ToTable("core_tariff", (string)null);
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.TransactionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChargingStationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumptionType")
                        .HasColumnType("text");

                    b.Property<int?>("EVSEId")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("IdTokenId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("Offline")
                        .HasColumnType("boolean");

                    b.Property<int>("SeqNo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalConsuption")
                        .HasColumnType("numeric");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TriggerReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("IdTokenId");

                    b.HasIndex("SeqNo");

                    b.HasIndex("TransactionId");

                    b.HasIndex("ChargingStationId", "TransactionId");

                    b.ToTable("core_transactions_event", (string)null);
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.TransactionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChargingStationId")
                        .HasColumnType("uuid");

                    b.Property<string>("EndReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EvseConnectorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdTokenId")
                        .HasColumnType("uuid");

                    b.Property<string>("StartReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalMeteredValue")
                        .HasColumnType("numeric");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EvseConnectorId");

                    b.HasIndex("IdTokenId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("ChargingStationId", "TransactionId");

                    b.ToTable("core_transactions_snapshot", (string)null);
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.Authorization.AuthorizationDetails", b =>
                {
                    b.HasOne("Medinilla.DataAccess.Relational.Models.ChargingStation", "ChargingStation")
                        .WithOne("AuthorizationDetails")
                        .HasForeignKey("Medinilla.DataAccess.Relational.Models.Authorization.AuthorizationDetails", "ChargingStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingStation");
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.Authorization.IdToken", b =>
                {
                    b.HasOne("Medinilla.DataAccess.Relational.Models.Authorization.AuthorizationUser", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medinilla.DataAccess.Relational.Models.ChargingStation", "ChargingStation")
                        .WithMany("IdTokens")
                        .HasForeignKey("ChargingStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingStation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.ChargingStation", b =>
                {
                    b.HasOne("Medinilla.DataAccess.Relational.Models.Account", "Account")
                        .WithMany("ChargingStations")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.EvseConnector", b =>
                {
                    b.HasOne("Medinilla.DataAccess.Relational.Models.ChargingStation", "ChargingStation")
                        .WithMany("EvseConnectors")
                        .HasForeignKey("ChargingStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingStation");
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.Tariff", b =>
                {
                    b.HasOne("Medinilla.DataAccess.Relational.Models.ChargingStation", "ChargingStation")
                        .WithMany("Tariffs")
                        .HasForeignKey("ChargingStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingStation");
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.TransactionEvent", b =>
                {
                    b.HasOne("Medinilla.DataAccess.Relational.Models.ChargingStation", "ChargingStation")
                        .WithMany("TransactionEvents")
                        .HasForeignKey("ChargingStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medinilla.DataAccess.Relational.Models.Authorization.IdToken", "IdToken")
                        .WithMany("TransactionEvents")
                        .HasForeignKey("IdTokenId");

                    b.Navigation("ChargingStation");

                    b.Navigation("IdToken");
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.TransactionSnapshot", b =>
                {
                    b.HasOne("Medinilla.DataAccess.Relational.Models.ChargingStation", "ChargingStation")
                        .WithMany("TransactionSnapshots")
                        .HasForeignKey("ChargingStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medinilla.DataAccess.Relational.Models.EvseConnector", "EvseConnector")
                        .WithMany()
                        .HasForeignKey("EvseConnectorId");

                    b.HasOne("Medinilla.DataAccess.Relational.Models.Authorization.IdToken", "IdToken")
                        .WithMany("TransactionSnapshots")
                        .HasForeignKey("IdTokenId");

                    b.Navigation("ChargingStation");

                    b.Navigation("EvseConnector");

                    b.Navigation("IdToken");
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.Account", b =>
                {
                    b.Navigation("ChargingStations");
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.Authorization.AuthorizationUser", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.Authorization.IdToken", b =>
                {
                    b.Navigation("TransactionEvents");

                    b.Navigation("TransactionSnapshots");
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.ChargingStation", b =>
                {
                    b.Navigation("AuthorizationDetails")
                        .IsRequired();

                    b.Navigation("EvseConnectors");

                    b.Navigation("IdTokens");

                    b.Navigation("Tariffs");

                    b.Navigation("TransactionEvents");

                    b.Navigation("TransactionSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
