<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="Contracts\ocpp\ChargingStation.proto" />
    <Protobuf Include="Contracts\ocpp\CommandExecution.proto" />
    <Protobuf Include="Contracts\ocpp\IdToken.proto" />
    <Protobuf Include="Contracts\ocpp\ResetType.proto" />
    <Protobuf Include="Contracts\ocpp\UserSetVariablesRequest.proto" />
    <Protobuf Include="Contracts\ocpp\UserGetVariablesRequest.proto" />
    <Protobuf Include="Contracts\query\Charger.proto" />
    <Protobuf Include="Contracts\query\Connector.proto" />
    <Protobuf Include="Contracts\query\TransactionSnapshot.proto" />
    <Protobuf Include="Service\ocpp\Error.proto" />
    <Protobuf Include="Service\ocpp\SetVariablesAPI.proto" />
    <Protobuf Include="Service\ocpp\GetVariablesAPI.proto" />
    <Protobuf Include="Service\ocpp\GetBaseReportAPI.proto" />
    <Protobuf Include="Service\ocpp\ResetAPI.proto" />
    <Protobuf Include="Service\ocpp\RequestStartTransactionAPI.proto" />
    <Protobuf Include="Service\ocpp\RequestStopTransactionAPI.proto" />
    <Protobuf Include="Service\ocpp\FetchExecutedCommandsAPI.proto" />
    <Protobuf Include="Service\ocpp\OcppService.proto" />
    <Protobuf Include="Service\query\GetChargerAPI.proto" />
    <Protobuf Include="Service\query\ListChargersAPI.proto" />
    <Protobuf Include="Service\query\ListTransactionSnapshotsAPI.proto" />
    <Protobuf Include="Service\query\QueryService.proto" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.29.3" />
    <PackageReference Include="Grpc.Core.Api" Version="2.67.0" />
    <PackageReference Include="Grpc.Tools" Version="2.70.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
