// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CommunicationChannelSignal.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Medinilla.Core.SharedContracts.Comms {

  /// <summary>Holder for reflection information generated from CommunicationChannelSignal.proto</summary>
  public static partial class CommunicationChannelSignalReflection {

    #region Descriptor
    /// <summary>File descriptor for CommunicationChannelSignal.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommunicationChannelSignalReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBDb21tdW5pY2F0aW9uQ2hhbm5lbFNpZ25hbC5wcm90bxIkbWVkaW5pbGxh",
            "LmNvcmUuU2hhcmVkQ29udHJhY3RzLmNvbW1zGhZvY3BwL09jcHBNZXNzYWdl",
            "LnByb3RvIqQBChpDb21tdW5pY2F0aW9uQ2hhbm5lbFNpZ25hbBI9CgRGbGFn",
            "GAEgASgOMi8ubWVkaW5pbGxhLmNvcmUuU2hhcmVkQ29udHJhY3RzLmNvbW1z",
            "LkNvbW1zRmxhZxJHCgdNZXNzYWdlGAIgASgLMjYubWVkaW5pbGxhLmNvcmUu",
            "U2hhcmVkQ29udHJhY3RzLmNvbW1zLm9jcHAuT2NwcE1lc3NhZ2UqIAoJQ29t",
            "bXNGbGFnEgcKA1NldBAAEgoKBlJlbW92ZRABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Medinilla.Core.SharedContracts.Comms.Ocpp.OcppMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Medinilla.Core.SharedContracts.Comms.CommsFlag), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Medinilla.Core.SharedContracts.Comms.CommunicationChannelSignal), global::Medinilla.Core.SharedContracts.Comms.CommunicationChannelSignal.Parser, new[]{ "Flag", "Message" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum CommsFlag {
    [pbr::OriginalName("Set")] Set = 0,
    [pbr::OriginalName("Remove")] Remove = 1,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CommunicationChannelSignal : pb::IMessage<CommunicationChannelSignal>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CommunicationChannelSignal> _parser = new pb::MessageParser<CommunicationChannelSignal>(() => new CommunicationChannelSignal());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CommunicationChannelSignal> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Medinilla.Core.SharedContracts.Comms.CommunicationChannelSignalReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CommunicationChannelSignal() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CommunicationChannelSignal(CommunicationChannelSignal other) : this() {
      flag_ = other.flag_;
      message_ = other.message_ != null ? other.message_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CommunicationChannelSignal Clone() {
      return new CommunicationChannelSignal(this);
    }

    /// <summary>Field number for the "Flag" field.</summary>
    public const int FlagFieldNumber = 1;
    private global::Medinilla.Core.SharedContracts.Comms.CommsFlag flag_ = global::Medinilla.Core.SharedContracts.Comms.CommsFlag.Set;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Medinilla.Core.SharedContracts.Comms.CommsFlag Flag {
      get { return flag_; }
      set {
        flag_ = value;
      }
    }

    /// <summary>Field number for the "Message" field.</summary>
    public const int MessageFieldNumber = 2;
    private global::Medinilla.Core.SharedContracts.Comms.Ocpp.OcppMessage message_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Medinilla.Core.SharedContracts.Comms.Ocpp.OcppMessage Message {
      get { return message_; }
      set {
        message_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CommunicationChannelSignal);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CommunicationChannelSignal other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Flag != other.Flag) return false;
      if (!object.Equals(Message, other.Message)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Flag != global::Medinilla.Core.SharedContracts.Comms.CommsFlag.Set) hash ^= Flag.GetHashCode();
      if (message_ != null) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Flag != global::Medinilla.Core.SharedContracts.Comms.CommsFlag.Set) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Flag);
      }
      if (message_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Flag != global::Medinilla.Core.SharedContracts.Comms.CommsFlag.Set) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Flag);
      }
      if (message_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Flag != global::Medinilla.Core.SharedContracts.Comms.CommsFlag.Set) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Flag);
      }
      if (message_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CommunicationChannelSignal other) {
      if (other == null) {
        return;
      }
      if (other.Flag != global::Medinilla.Core.SharedContracts.Comms.CommsFlag.Set) {
        Flag = other.Flag;
      }
      if (other.message_ != null) {
        if (message_ == null) {
          Message = new global::Medinilla.Core.SharedContracts.Comms.Ocpp.OcppMessage();
        }
        Message.MergeFrom(other.Message);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Flag = (global::Medinilla.Core.SharedContracts.Comms.CommsFlag) input.ReadEnum();
            break;
          }
          case 18: {
            if (message_ == null) {
              Message = new global::Medinilla.Core.SharedContracts.Comms.Ocpp.OcppMessage();
            }
            input.ReadMessage(Message);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Flag = (global::Medinilla.Core.SharedContracts.Comms.CommsFlag) input.ReadEnum();
            break;
          }
          case 18: {
            if (message_ == null) {
              Message = new global::Medinilla.Core.SharedContracts.Comms.Ocpp.OcppMessage();
            }
            input.ReadMessage(Message);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
