// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WampResult.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Medinilla.Core.SharedContracts.Comms.Ocpp {

  /// <summary>Holder for reflection information generated from WampResult.proto</summary>
  public static partial class WampResultReflection {

    #region Descriptor
    /// <summary>File descriptor for WampResult.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WampResultReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBXYW1wUmVzdWx0LnByb3RvEiltZWRpbmlsbGEuY29yZS5TaGFyZWRDb250",
            "cmFjdHMuY29tbXMub2NwcCJ4CgpXYW1wUmVzdWx0EhMKBlJlc3VsdBgBIAEo",
            "DEgAiAEBEhIKBUVycm9yGAIgASgMSAGIAQESEgoKUmV0dXJuVG9DUxgDIAEo",
            "CBIYChBDbGllbnRJZGVudGlmaWVyGAQgASgJQgkKB19SZXN1bHRCCAoGX0Vy",
            "cm9yYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Medinilla.Core.SharedContracts.Comms.Ocpp.WampResult), global::Medinilla.Core.SharedContracts.Comms.Ocpp.WampResult.Parser, new[]{ "Result", "Error", "ReturnToCS", "ClientIdentifier" }, new[]{ "Result", "Error" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WampResult : pb::IMessage<WampResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WampResult> _parser = new pb::MessageParser<WampResult>(() => new WampResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WampResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Medinilla.Core.SharedContracts.Comms.Ocpp.WampResultReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WampResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WampResult(WampResult other) : this() {
      result_ = other.result_;
      error_ = other.error_;
      returnToCS_ = other.returnToCS_;
      clientIdentifier_ = other.clientIdentifier_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WampResult Clone() {
      return new WampResult(this);
    }

    /// <summary>Field number for the "Result" field.</summary>
    public const int ResultFieldNumber = 1;
    private readonly static pb::ByteString ResultDefaultValue = pb::ByteString.Empty;

    private pb::ByteString result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Result {
      get { return result_ ?? ResultDefaultValue; }
      set {
        result_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "Result" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasResult {
      get { return result_ != null; }
    }
    /// <summary>Clears the value of the "Result" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearResult() {
      result_ = null;
    }

    /// <summary>Field number for the "Error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private readonly static pb::ByteString ErrorDefaultValue = pb::ByteString.Empty;

    private pb::ByteString error_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Error {
      get { return error_ ?? ErrorDefaultValue; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "Error" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasError {
      get { return error_ != null; }
    }
    /// <summary>Clears the value of the "Error" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearError() {
      error_ = null;
    }

    /// <summary>Field number for the "ReturnToCS" field.</summary>
    public const int ReturnToCSFieldNumber = 3;
    private bool returnToCS_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ReturnToCS {
      get { return returnToCS_; }
      set {
        returnToCS_ = value;
      }
    }

    /// <summary>Field number for the "ClientIdentifier" field.</summary>
    public const int ClientIdentifierFieldNumber = 4;
    private string clientIdentifier_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientIdentifier {
      get { return clientIdentifier_; }
      set {
        clientIdentifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WampResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WampResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (Error != other.Error) return false;
      if (ReturnToCS != other.ReturnToCS) return false;
      if (ClientIdentifier != other.ClientIdentifier) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasResult) hash ^= Result.GetHashCode();
      if (HasError) hash ^= Error.GetHashCode();
      if (ReturnToCS != false) hash ^= ReturnToCS.GetHashCode();
      if (ClientIdentifier.Length != 0) hash ^= ClientIdentifier.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasResult) {
        output.WriteRawTag(10);
        output.WriteBytes(Result);
      }
      if (HasError) {
        output.WriteRawTag(18);
        output.WriteBytes(Error);
      }
      if (ReturnToCS != false) {
        output.WriteRawTag(24);
        output.WriteBool(ReturnToCS);
      }
      if (ClientIdentifier.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ClientIdentifier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasResult) {
        output.WriteRawTag(10);
        output.WriteBytes(Result);
      }
      if (HasError) {
        output.WriteRawTag(18);
        output.WriteBytes(Error);
      }
      if (ReturnToCS != false) {
        output.WriteRawTag(24);
        output.WriteBool(ReturnToCS);
      }
      if (ClientIdentifier.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ClientIdentifier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasResult) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Result);
      }
      if (HasError) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Error);
      }
      if (ReturnToCS != false) {
        size += 1 + 1;
      }
      if (ClientIdentifier.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientIdentifier);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WampResult other) {
      if (other == null) {
        return;
      }
      if (other.HasResult) {
        Result = other.Result;
      }
      if (other.HasError) {
        Error = other.Error;
      }
      if (other.ReturnToCS != false) {
        ReturnToCS = other.ReturnToCS;
      }
      if (other.ClientIdentifier.Length != 0) {
        ClientIdentifier = other.ClientIdentifier;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Result = input.ReadBytes();
            break;
          }
          case 18: {
            Error = input.ReadBytes();
            break;
          }
          case 24: {
            ReturnToCS = input.ReadBool();
            break;
          }
          case 34: {
            ClientIdentifier = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Result = input.ReadBytes();
            break;
          }
          case 18: {
            Error = input.ReadBytes();
            break;
          }
          case 24: {
            ReturnToCS = input.ReadBool();
            break;
          }
          case 34: {
            ClientIdentifier = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
