// <auto-generated />
using System;
using Medinilla.DataAccess.Relational;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Medinilla.DataAccess.Migrations
{
    [DbContext(typeof(MedinillaOcppDbContext))]
    [Migration("20241130131154_Update-TransactionsIndices")]
    partial class UpdateTransactionsIndices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.ChargingStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LatestBootNotificationReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientIdentifier");

                    b.ToTable("charging_station", (string)null);
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.EvseConnector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChargingStationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("integer");

                    b.Property<string>("ConnectorStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EvseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChargingStationId");

                    b.ToTable("evse_connector", (string)null);
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChargingStationId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ChargingStationId");

                    b.ToTable("tariff", (string)null);
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.TransactionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChargingStationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("EVSEId")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdToken")
                        .HasColumnType("text");

                    b.Property<decimal>("MeteredValue")
                        .HasColumnType("numeric");

                    b.Property<bool?>("Offline")
                        .HasColumnType("boolean");

                    b.Property<int>("SeqNo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TriggerReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("SeqNo");

                    b.HasIndex("TransactionId");

                    b.HasIndex("ChargingStationId", "TransactionId");

                    b.ToTable("transactions_event", (string)null);
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.TransactionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChargingStationId")
                        .HasColumnType("uuid");

                    b.Property<string>("EndReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EvseConnectorId")
                        .HasColumnType("uuid");

                    b.Property<string>("StartReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalMeteredValue")
                        .HasColumnType("numeric");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EvseConnectorId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("ChargingStationId", "TransactionId");

                    b.ToTable("transactions_snapshot", (string)null);
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.EvseConnector", b =>
                {
                    b.HasOne("Medinilla.DataAccess.Relational.Models.ChargingStation", "ChargingStation")
                        .WithMany("EvseConnectors")
                        .HasForeignKey("ChargingStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingStation");
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.Tariff", b =>
                {
                    b.HasOne("Medinilla.DataAccess.Relational.Models.ChargingStation", "ChargingStation")
                        .WithMany("Tariffs")
                        .HasForeignKey("ChargingStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingStation");
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.TransactionEvent", b =>
                {
                    b.HasOne("Medinilla.DataAccess.Relational.Models.ChargingStation", "ChargingStation")
                        .WithMany("TransactionEvents")
                        .HasForeignKey("ChargingStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingStation");
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.TransactionSnapshot", b =>
                {
                    b.HasOne("Medinilla.DataAccess.Relational.Models.ChargingStation", "ChargingStation")
                        .WithMany("TransactionSnapshots")
                        .HasForeignKey("ChargingStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medinilla.DataAccess.Relational.Models.EvseConnector", "EvseConnector")
                        .WithMany()
                        .HasForeignKey("EvseConnectorId");

                    b.Navigation("ChargingStation");

                    b.Navigation("EvseConnector");
                });

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.ChargingStation", b =>
                {
                    b.Navigation("EvseConnectors");

                    b.Navigation("Tariffs");

                    b.Navigation("TransactionEvents");

                    b.Navigation("TransactionSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
