// <auto-generated />
using System;
using Medinilla.DataAccess.Relational;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Medinilla.DataAccess.Migrations
{
    [DbContext(typeof(MedinillaOcppDbContext))]
    [Migration("20241127222149_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Medinilla.DataAccess.Relational.Models.Transaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<int>("SeqNo")
                        .HasColumnType("integer");

                    b.Property<int?>("EVSEId")
                        .HasColumnType("integer");

                    b.Property<string>("IdToken")
                        .HasColumnType("text");

                    b.Property<bool>("Offline")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TransactionId", "SeqNo");

                    b.ToTable("transactions_event");
                });
#pragma warning restore 612, 618
        }
    }
}
